# permissions for end users to view cars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: car-viewer-role
rules:
- apiGroups:
  - home.lanford.io
  resources:
  - cars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - home.lanford.io
  resources:
  - cars/status
  verbs:
  - get
