
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - home.lanford.io
  resources:
  - cars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - home.lanford.io
  resources:
  - cars/finalizers
  verbs:
  - update
- apiGroups:
  - home.lanford.io
  resources:
  - cars/status
  verbs:
  - get
  - patch
  - update
